project:
  type: website
  output-dir: _site
  preview:
    port: 5896
    browser: true
  render:
    - "*.qmd"
    - "!fragments/"
  resources:
    - "class/"
    - "rubrics/"
    - "data/"
    - "content/"
    - "mini/"
    - "final/"
    - "templates/"

website:
  title: EMSE 4572 / 6572
  image: images/logo.png
  site-url: https://eda.seas.gwu.edu/2023-Fall/
  favicon: images/favicon.ico
  repo-url: https://github.com/emse-eda-gwu/2023-Fall
  repo-actions: [edit, issue]
  description: 'Course website for Fall 2023 semester of the EMSE course "Exploratory Data Analysis" at GWU'
  search: true
  open-graph:
    locale: es_ES
    site-name: https://eda.seas.gwu.edu/
  twitter-card:
    creator: "@johnhelveston"
    site: "@johnhelveston"
    image: "images/logo-square.png"
    card-style: summary
  sidebar:
    style: "docked"
    background: "dark"
    collapse-level: 1
    search: true
    contents:
      - text: Home
        icon: house-door-fill
        href: index.qmd
      - text: Syllabus
        icon: map-fill
        href: syllabus.qmd
      - text: Schedule
        icon: table
        href: schedule.qmd
      - section: Mini Projects
        icon: pencil-square
        contents:
          - text: "1: Data Cleaning"
            href: mini/1-data-cleaning.qmd
          - text: "2: Exploring Data"
            href: mini/2-exploring-data.qmd
          - text: "3: Re-design" 
            href: mini/3-redesign.qmd
      - section: Final Project
        icon: search
        contents:
          - text: Overview
            href: final/0-overview.qmd
          - text: Proposal
            href: final/1-proposal.qmd
          - text: Progress Report 
            href: final/2-progress-report.qmd
          - text: Final Report 
            href: final/3-final-report.qmd
          - text: Final Presentation 
            href: final/4-presentation.qmd
          - text: Examples
            href: final/examples.qmd
      - text: Software
        icon: download
        href: software.qmd
      - text: Finding Data
        icon: database-fill
        href: finding-data.qmd
      - text: References
        icon: bookmark-fill
        href: references.qmd
      - text: Slack
        icon: slack
        href: https://emse-eda-s23.slack.com
      - text: "Schedule a call w/Prof. Helveston"
        icon: clock-fill
        href: https://jhelvy.appointlet.com/b/professor-helveston
      - section: Other
        icon: question-circle-fill
        contents:
          - text: About
            icon: question-circle-fill
            href: about.qmd
          - text: License
            icon: award-fill
            href: LICENSE.qmd
          - text: Contact
            icon: envelope-fill
            href: mailto:jph@gwu.edu
          - text: Source files
            icon: github
            href: https://github.com/emse-eda-gwu/2023-Fall
  page-footer:
    center:
      - text: '© 2023 John Paul Helveston <a href="LICENSE.html"><i class="fab fa-creative-commons"></i><i class="fab fa-creative-commons-by"></i><i class="fab fa-creative-commons-sa"></i></a><br><i class="far fa-calendar-alt"></i> {{< var weekday >}} | <i class="far fa-clock"></i> {{< var time >}} | <a href="{{< var room_url >}}"><i class="fa fa-map-marker-alt"></i> {{< var room >}}</a> | <a href="https://www.jhelvy.com"><i class="fas fa-user"></i> Dr. John Paul Helveston</a> | <a href="mailto:{{< var email >}}"><i class="fas fa-envelope"></i> {{< var email >}}</a> | <a href="{{< var repo >}}"><i class="fab fa-github"></i></a>'

format:
  html:
    theme: flatly
    css: styles.css
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false

filters:
    - schedule.lua
