---
title: Schedule
toc: false
execute:
  echo: false
  warning: false
  message: false
---

All assignments are due by 11:59pm on the due date.

```{r}
#| echo: false
source("_common.R")
```

```{r}
# NOTE: The schedule.lua file is inserted as a filter in _quarto.yml to 
# avoid the insertion of a <colgroup> in the html around this table: 
# https://github.com/jgm/pandoc/issues/8139

library(tidyverse)
library(kableExtra)

schedule <- get_schedule() 
names(schedule) <- str_to_title(names(schedule))
schedule %>%
  rename(
      `Mini Projects` = Mini,
      `Final Projects` = Final,
      `Weekly HW` = Assignments
  ) %>%
  select(
      Week, Date = Date_md, Class, `Weekly HW`, `Mini Projects`,
      `Final Projects`
  ) %>%
  kable(format = 'html', escape = FALSE,
        align = c('c', 'c', 'l', 'l', 'l', 'l')) %>%
  kable_styling(full_width = F, bootstrap_options = c("striped", "hover")) %>%
  column_spec(column = 3, width = '19em') 

# Add highlighting based on current week if we're still in the semester
highlight <- which(Sys.Date() > (schedule$Date))
if (Sys.Date() <= ymd("2023-05-12")) {
  done <- done %>%
    row_spec(highlight, background = "#C6C6C6")
}

done
```



